### ISSUE TITLE
Running in a vagrant box has problems with grails port 4440

### ISSUE THREAD

**Issue by staylorx** [New-Edge-Engineering/ansible-rundeck#10]
The install goes smoothly and the login page comes up at port 4440 (defined from framework.properties). But once logged in the grails host and port from rundeck-config.properties takes over and the page 404's.

**Comment by mat-green** [comment]
This was originally designed to work behind nginx on port 80, which why the port 4440 is not included in the grailsURL. Happy to add this as default for role.

**Comment by mat-green** [comment]
Should be reolved within release v0.0.8
