### ISSUE TITLE
rundeck_targeting_version is not registered in RHEL / CentOS configuration

### ISSUE THREAD

**Issue by rdanilin** [New-Edge-Engineering/ansible-rundeck#14]
Hey,

I'm trying to run this role on CentOS 7, during execution I see below error: 
``
TASK: [ansible-rundeck | Rundeck - PostgreSQL | ensure database is used to store projects] ***
fatal: [default] => Failed to template {% if rundeck_targeting_version.stdout|version_compare('2.5.0', '>=') %} True {% else %} False {% endif %}: Version comparison: 'dict object' has no attribute 'stdout'

FATAL: all hosts have already failed -- aborting
``

**Comment by mat-green** [comment]
Hey, what version of ansible are you using?

**Comment by rdanilin** [comment]
Default one I suppose. For now I just commented failed string and it works.

**Comment by cmcwales2k** [comment]
Hi
line 107 "when: rundeck_targeting_version.stdout|version_compare('2.5.0', '>=')" has not been removed in "configure_for_mysql.yml", but has been removed from  "configure_for_postgresql.yml". 

Is the when statement actually required?
