### ISSUE TITLE
Ubuntu 16.04: make sure python-setuptools is present

### ISSUE THREAD

**Issue by jardleex** [New-Edge-Engineering/ansible-rundeck#23]
Hi,

please check if you can confirm.
I tried to apply the role on a Ubuntu 16.04.1 VM and it failed here.
`
TASK [New-Edge-Engineering.rundeck : Rundeck | Install supporting python packages] ***
Friday 30 September 2016  14:00:05 +0200 (0:00:01.313)       0:00:07.146 ****** 
failed: [opsdeck01.prv.cgn.sprd.net] (item=httplib2) => {"cmd": "/usr/bin/pip install httplib2", "failed": true, "item": "httplib2", "msg": "stdout: Collecting httplib2\n  Using cached httplib2-0.9.2.zip\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n    ImportError: No module named setuptools\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-MoUBTV/httplib2/\nYou are using pip version 8.1.1, however version 8.1.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}
`

Reason was/is that the debian package **python-setuptools** is missing. I installed it by hand and the step from above was successful.

If you can confirm, may you add **python-setuptools** to the step **Rundeck | Install supporting packages** in install_debian.yml

Thanks a lot.

**Comment by mat-green** [comment]
Fixed
