### ISSUE TITLE
develop branch looks broken (so look the tags 17.02.12/13)

### ISSUE THREAD

**Issue by zonArt** [New-Edge-Engineering/ansible-rundeck#26]
Hi,

Thank you for this role. I'd like to notify you that PR #18 (and more specifically commit d7e0402584585ddeded01eb54c4a47cd4a459ac9) seem to have broken execution of this role by removing the `register: rundeck_targeting_version` in install_debian.yml needed in both postgresql.yml and mysql.yml (at lines 107 and 92 respectively)

**Comment by mat-green** [comment]
Thank for point this out.

**Comment by zonArt** [comment]
You're welcome.
By the way, may I ask you which development workflow are you using ? I see develop and master branch (both of which not fully functional), I guessed that all the v0.0.x tags are coming from master and the two latest 17.02.12 and 17.02.13 from develop, am I right ?

So my question is what is master used for and what's the purpose of develop ? Sorry I'm lost (but wishing to help), might be silly questions.

**Comment by mat-green** [comment]
Hello,

Normally follow git flow and tagging from master completed work. I must have missed the last step in the recent releases - my bad.

**Comment by mat-green** [comment]
Fixed in the 17.03.14 release
